language: node_js
node_js:
 - "6.11.3"

cache:
  directories:
    - "node_modules"

before_script:
  - npm run build

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)